#!/bin/sh
# XXX chroot and user don't work with inetd

host="smtp.yandex.ru:587"
port=9050

if [ -n "$1" ]; then
	user=",user=$1"
fi

if [ -n "$2" ]; then
	chroot=",chroot-early=$2"
fi

@PREFIX@/bin/socat -ly "STDIN${chroot}${user}" \
                       "SOCKS4A:127.0.0.1:${host},socksport=${port}"
