#!/bin/sh

user=webuser
tz=Europe/London
display=127.0.0.1:0.0

exec /usr/bin/env -i \
	TZ=${tz}      \
	USER=${user}   \
	LOGNAME=${user} \
	HOME=/${user}    \
	DISPLAY=${display} \
	/usr/sbin/chroot -u ${user} /home/${user}-chroot \
		@PREFIX@/bin/links -only-proxies 1 -g "$@"
