#!/bin/sh

user=webuser
tz=Europe/London
display=127.0.0.1:0.0
proxy=127.0.0.1:9050 # tor

exec /usr/bin/env -i \
	TZ=${tz}      \
	USER=${user}   \
	LOGNAME=${user} \
	HOME=/${user}    \
	DISPLAY=${display} \
	/usr/sbin/chroot -u ${user} /home/${user}-chroot \
		@PREFIX@/bin/links -socks-proxy "${proxy}" -g "$@"
