#!/bin/sh

set -e

user=webuser
home=/${user}
tz=Europe/London
display=127.0.0.1${DISPLAY:?}
chroot="/home/${user}-chroot"
devroot="${chroot}/dev"

if ! /bin/dd if=${devroot}/random of=${devroot}/null bs=1 count=1 msgfmt=quiet; then
	/sbin/mount_tmpfs -s 65536 -n 128 -m 0755 tmpfs ${devroot}
	trap "/sbin/umount ${devroot} 2>/dev/null" EXIT
	cd ${devroot}
	/dev/MAKEDEV std crypto audio video
	cd "${OLDPWD}"
fi

/usr/bin/env -i  \
	TZ=${tz}   \
	HOME=${home} \
	USER=${user}   \
	LOGNAME=${user}  \
	DISPLAY=${display} \
	/usr/sbin/chroot -u ${user} ${chroot} \
		@PREFIX@/lib/tor-browser/tor-browser-bin "$@"
