#!/bin/sh

user=webuser
home=/${user}
tz=Europe/London
display=127.0.0.1:0.0

cd "/home/${user}-chroot"

if [ -r ${user}.tgz && ! -d tmp/webuser ]; then
	(cd tmp && tar xzf ../${user}.tgz)
	home=/tmp/${user}
fi

exec /usr/bin/env -i  \
	TZ=${tz}       \
	HOME=${home}    \
	USER=${user}     \
	LOGNAME=${user}   \
	DISPLAY=${display} \
	/usr/sbin/chroot -u ${user} /home/${user}-chroot \
		@PREFIX@/bin/firefox "$@"
